-- Seed dos checklists residencial e comercial/industrial.
-- Editável depois via tabela (não fixo no código).

insert into public.vistoria_checklist_templates (tipo_imovel, secao, item, ordem) values
('residencial', 'Elétrica', 'tomadas', 1),
('residencial', 'Elétrica', 'interruptores', 2),
('residencial', 'Elétrica', 'lâmpadas e luminárias', 3),
('residencial', 'Elétrica', 'quadro de disjuntores', 4),
('residencial', 'Elétrica', 'campainha / interfone', 5),
('residencial', 'Hidráulica', 'torneiras', 6),
('residencial', 'Hidráulica', 'vazamentos e infiltrações', 7),
('residencial', 'Hidráulica', 'ralos e escoamento', 8),
('residencial', 'Hidráulica', 'caixa d''água / aquecedor (se houver)', 9),
('residencial', 'Portas e fechaduras', 'portas internas', 10),
('residencial', 'Portas e fechaduras', 'porta de entrada', 11),
('residencial', 'Portas e fechaduras', 'fechaduras e chaves', 12),
('residencial', 'Portas e fechaduras', 'dobradiças e alinhamento', 13),
('residencial', 'Janelas e vidros', 'vidros (trincas)', 14),
('residencial', 'Janelas e vidros', 'abertura e fechamento', 15),
('residencial', 'Janelas e vidros', 'fechos e trincos', 16),
('residencial', 'Janelas e vidros', 'telas / persianas', 17),
('residencial', 'Paredes e pintura', 'estado da pintura', 18),
('residencial', 'Paredes e pintura', 'manchas / infiltração / mofo', 19),
('residencial', 'Paredes e pintura', 'furos e fissuras', 20),
('residencial', 'Pisos e rodapés', 'estado do piso', 21),
('residencial', 'Pisos e rodapés', 'rejunte / peças soltas', 22),
('residencial', 'Pisos e rodapés', 'rodapés', 23),
('residencial', 'Forro / teto', 'estado do teto', 24),
('residencial', 'Forro / teto', 'manchas / infiltração', 25),
('residencial', 'Sala', 'paredes', 26),
('residencial', 'Sala', 'piso', 27),
('residencial', 'Sala', 'janelas', 28),
('residencial', 'Sala', 'iluminação', 29),
('residencial', 'Sala', 'tomadas', 30),
('residencial', 'Cozinha', 'bancada e pia', 31),
('residencial', 'Cozinha', 'armários e gavetas', 32),
('residencial', 'Cozinha', 'azulejos', 33),
('residencial', 'Cozinha', 'torneira e sifão', 34),
('residencial', 'Cozinha', 'pontos de gás', 35),
('residencial', 'Cozinha', 'eletrodomésticos (se mobiliado)', 36),
('residencial', 'Cozinha', 'paredes', 37),
('residencial', 'Cozinha', 'piso', 38),
('residencial', 'Cozinha', 'janela', 39),
('residencial', 'Área de serviço', 'tanque / pia', 40),
('residencial', 'Área de serviço', 'pontos de água (máquina)', 41),
('residencial', 'Área de serviço', 'ralo', 42),
('residencial', 'Área de serviço', 'paredes', 43),
('residencial', 'Área de serviço', 'piso', 44),
('residencial', 'Banheiro(s)', 'vaso sanitário', 45),
('residencial', 'Banheiro(s)', 'pia / cuba', 46),
('residencial', 'Banheiro(s)', 'box / chuveiro', 47),
('residencial', 'Banheiro(s)', 'espelho e acessórios', 48),
('residencial', 'Banheiro(s)', 'azulejos / rejunte', 49),
('residencial', 'Banheiro(s)', 'ventilação', 50),
('residencial', 'Banheiro(s)', 'paredes', 51),
('residencial', 'Banheiro(s)', 'piso', 52),
('residencial', 'Quarto(s)', 'paredes', 53),
('residencial', 'Quarto(s)', 'piso', 54),
('residencial', 'Quarto(s)', 'janelas', 55),
('residencial', 'Quarto(s)', 'armários embutidos (se houver)', 56),
('residencial', 'Quarto(s)', 'iluminação e tomadas', 57),
('residencial', 'Varanda / Sacada', 'piso', 58),
('residencial', 'Varanda / Sacada', 'guarda-corpo', 59),
('residencial', 'Varanda / Sacada', 'vidros', 60),
('residencial', 'Varanda / Sacada', 'ralo', 61),
('residencial', 'Garagem / Vaga', 'demarcação e piso', 62),
('residencial', 'Garagem / Vaga', 'portão / controle', 63),
('residencial', 'Segurança', 'detectores de fumaça (se houver)', 64),
('residencial', 'Segurança', 'alarme / câmeras (se houver)', 65);

insert into public.vistoria_checklist_templates (tipo_imovel, secao, item, ordem) values
('comercial', 'Estrutura e cobertura', 'telhado / cobertura', 1),
('comercial', 'Estrutura e cobertura', 'estrutura (pilares, vigas)', 2),
('comercial', 'Estrutura e cobertura', 'calhas e rufos', 3),
('comercial', 'Estrutura e cobertura', 'pé-direito e vedações', 4),
('comercial', 'Piso', 'piso (concreto / epóxi / cerâmico)', 5),
('comercial', 'Piso', 'trincas e desnível', 6),
('comercial', 'Piso', 'observação de capacidade de carga', 7),
('comercial', 'Instalações elétricas', 'quadro de força / entrada de energia', 8),
('comercial', 'Instalações elétricas', 'trifásico e capacidade (kVA)', 9),
('comercial', 'Instalações elétricas', 'tomadas industriais', 10),
('comercial', 'Instalações elétricas', 'iluminação (galpão e áreas)', 11),
('comercial', 'Instalações elétricas', 'aterramento / SPDA (para-raios)', 12),
('comercial', 'Instalações hidráulicas', 'pontos de água', 13),
('comercial', 'Instalações hidráulicas', 'esgoto e caixas', 14),
('comercial', 'Instalações hidráulicas', 'vazamentos', 15),
('comercial', 'Portões e docas', 'portões (manual / automático)', 16),
('comercial', 'Portões e docas', 'docas / plataformas de carga', 17),
('comercial', 'Portões e docas', 'controles de acesso', 18),
('comercial', 'Sistema de incêndio', 'extintores', 19),
('comercial', 'Sistema de incêndio', 'hidrantes', 20),
('comercial', 'Sistema de incêndio', 'sprinklers / detecção', 21),
('comercial', 'Sistema de incêndio', 'sinalização, rotas de fuga e iluminação de emergência', 22),
('comercial', 'Sistema de incêndio', 'observação sobre AVCB e validade', 23),
('comercial', 'Áreas administrativas / escritórios', 'salas e divisórias', 24),
('comercial', 'Áreas administrativas / escritórios', 'piso, forro e pintura', 25),
('comercial', 'Áreas administrativas / escritórios', 'ar-condicionado', 26),
('comercial', 'Áreas administrativas / escritórios', 'elétrica, rede e telefonia', 27),
('comercial', 'Banheiros / vestiários', 'louças e metais', 28),
('comercial', 'Banheiros / vestiários', 'box / chuveiros', 29),
('comercial', 'Banheiros / vestiários', 'azulejos e ventilação', 30),
('comercial', 'Ventilação e exaustão', 'exaustores / ventilação natural', 31),
('comercial', 'Ventilação e exaustão', 'climatização', 32),
('comercial', 'Mezanino (se houver)', 'estrutura', 33),
('comercial', 'Mezanino (se houver)', 'escada', 34),
('comercial', 'Mezanino (se houver)', 'guarda-corpo', 35),
('comercial', 'Pátio / estacionamento / área externa', 'pavimentação', 36),
('comercial', 'Pátio / estacionamento / área externa', 'muros / cercas / portaria', 37),
('comercial', 'Pátio / estacionamento / área externa', 'drenagem', 38),
('comercial', 'Pátio / estacionamento / área externa', 'iluminação externa', 39),
('comercial', 'Segurança', 'câmeras / alarme', 40),
('comercial', 'Segurança', 'portaria / guarita', 41);
