-- Seed inicial do registro de imóveis para vistoria (imoveis_vistoria), a partir
-- da base de imóveis administrados (Notion). Apenas inserção de dados, não altera schema.
-- "Industrial" foi mapeado para tipo 'comercial' (mesma categoria de checklist usada no app).

insert into public.imoveis_vistoria (nome, endereco, tipo) values
('Tocantins Casa 8', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('Av Senador Roberto Simonsen, 1364', 'Av. Sen. Roberto Símonsen, 1364 - Santo Antônio, São Caetano do Sul', 'residencial'),
('Predio Rua Friburgo 172', 'R. Friburgo, 172 - Vila Francisco Matarazzo, Santo André', 'residencial'),
('Parco Toscana (Geral)', 'R. São Geraldo, 190 - Parque Bandeirante, Santo André', 'residencial'),
('Jorge Velho 75 e 105', 'R. Jorge Velho, 75 - Campestre, Santo André', 'comercial'),
('Casa Trav Teodoro Sampaio', 'R. Teodoro Sampaio, 13 - Cerâmica, São Caetano do Sul', 'residencial'),
('Sala 408 Think', 'Av. Marquês de S. Vicente, 230 - Várzea da Barra Funda, São Paulo', 'comercial'),
('Casa Carmine Perrella 442', 'R. Carmine Perrella, 442 - Mauá, São Caetano do Sul', 'residencial'),
('Cadoro 1806', 'R. Caio Prado, 363 - Consolação, São Paulo', 'residencial'),
('Casa Peruibe', 'R. Eduardo Linardi, 1206 - Jardim Barra de Jangadas, Peruíbe', 'residencial'),
('Network', 'Alameda Terracota, 215 - Santo Antônio, São Caetano do Sul', 'comercial'),
('Casa Rua Humberto de Campos nº 530 (Geral)', 'R. Humberto de Campos, 530 - São José, São Caetano do Sul', 'residencial'),
('Industrial', 'Avenida Industrial, 2350 - Campestre - Santo André', 'comercial'),
('Apto 42 Vetta', 'R. João Ribeiro, 327 - Campestre, Santo André', 'residencial'),
('Paulo Martinez (Geral)', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('Barra do Una', 'R. Joao Dos Passos Bittencourt, 180 - Praia do Una, São Sebastião', 'residencial'),
('Cadoro vaga 45M', 'R. Caio Prado, 363 - Consolação, São Paulo', 'residencial'),
('Apto Riviera', 'R. Passeio dos Galeões, 312 - São Lourenço, Bertioga', 'residencial'),
('Sumaré', 'R. Ernesto Barijan, 366 - Planalto do Sol, Sumaré', 'comercial'),
('Casa Sylvio Guimarães de Assis nº52', 'R. Sylvio Guimarães de Assis, São João Clímaco, São Paulo', 'residencial'),
('Eduardo Panades nº 51 x Alex', 'R. Eduardo Panadez, 51 - Jardim Seckler, São Paulo', 'comercial'),
('Casa 10', 'R. Justino Paixão, 547 - Jardim São Caetano, São Caetano do Sul', 'residencial'),
('Apto 184 B The Address', 'R. Justino Paixão, 317 - Jardim São Caetano, São Caetano do Sul', 'residencial'),
('Apto 181 B The Address', 'R. Justino Paixão, 317 - Jardim São Caetano, São Caetano do Sul', 'residencial'),
('Ilha Bela Vista do Conde', 'R. Conde D''Eu, 309 - Ribeirão, Ilha Bela', 'residencial'),
('Casa 81', 'R. Justino Paixão, 547 - Jardim São Caetano, São Caetano do Sul', 'residencial'),
('Tocantins 989 (Geral)', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('Casa das Estrada das Lágrimas', 'Estr. das Lágrimas, 2805 - São João Climaco, São Paulo', 'residencial'),
('PM Casa 22', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('Tocantins Casa 2', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('Tocantins Casa 5', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('PM Casa 17', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 15', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 12', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 13', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 3', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 21', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 5', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 23', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 1', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('Tocantins Casa 3', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('Parco Toscana 22', 'R. São Geraldo, 190 - Parque Bandeirante, Santo André', 'residencial'),
('Parco Toscana 24', 'R. São Geraldo, 190 - Parque Bandeirante, Santo André', 'residencial'),
('Parco Toscana 11', 'R. São Geraldo, 190 - Parque Bandeirante, Santo André', 'residencial'),
('Parco Toscana 42', 'R. São Geraldo, 190 - Parque Bandeirante, Santo André', 'residencial'),
('PM Casa 2', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 8', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 16', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 20', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 6', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 10', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 18', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('Tocantins Casa 6', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('Tocantins Casa 1', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('PM Casa 4', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 14', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('Tocantins Casa 7', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('Tocantins Casa 4', 'R. Tocantins, 989 - Nova Gerti, São Caetano do Sul', 'residencial'),
('Parco Toscana 131', 'R. São Geraldo, 190 - Parque Bandeirante, Santo André', 'residencial'),
('PM Casa 11', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 7', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 19', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial'),
('PM Casa 9', 'R. Paulo Martinez, 40 - Jardim Seckler, São Paulo', 'residencial');
